#!/usr/bin/env zsh

#
# Installation:
# - Run this script from dotfiles dir
# - Done!
#
# Note that the script is idempotent, but will silently overwrite any dotfiles that conflict
# use at own discretion, and back up any config you have before running the script
#
# In particular it will currently overwrite the entire .config folder
# fixme: only overwrite the entries in .config for which we actually have any files

echo ""
echo "Linking dotfiles"
echo ""
for file in $(ls -I 'LICENSE' -I 'bootstrap' -I 'wallpaper.png' -I 'setup'); do
  sym=$(pwd)/$file
  tar=$HOME/.$file

  if [[ -d $file ]]; then
       # Prevents nesting symlinks within previous sym
    if [[ -d $tar ]]; then rm -rf $tar; fi

    echo $tar/
    echo "-> $sym/"
  else
    echo $tar
    echo "-> $sym"
  fi

  ln -sfF "$(pwd)/$file" "$HOME/.$file"
done
echo ""

ln -sfF "$(pwd)/wallpaper.png" "$HOME/.local/share/backgrounds/"

