#!/usr/bin/env zsh

# Installation:
# - Run this script from dotfiles dir
# - Done!

# Link all the dots
echo ""
echo "Linking top-level dotfiles"
echo ""
for file in $(ls -I 'LICENSE' -I 'bootstrap' -I 'config' -I 'notes'); do
  echo $(pwd)/$file
  echo "-> $HOME/.$file"
  ln -sfF "$(pwd)/$file" "$HOME/.$file"
done
echo ""

# Create deltas for selected config dirs
echo "Populating .config"
echo ""
if [[ ! -d "$HOME/.config" ]]; then mkdir "$HOME/.config"; fi
for file in $(ls config); do

  if [[ -d "$HOME/.config/$file" ]]; then 
    rm -rf "$HOME/.config/$file"; 
  fi

  echo $(pwd)/config/$file
  echo "-> $HOME/.config/$file"
  ln -sfF "$(pwd)/config/$file" "$HOME/.config/$file"

done
echo ""

# Link config files in odd locations
# pass

# Setup prezto
cd zprezto
git pull
git submodule sync --recursive
git submodule update --init --recursive
zsh -c '\
  setopt EXTENDED_GLOB && \
  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do; \
    ln -sfF "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"; \
  done && \
  sudo chsh -s /bin/zsh'
cd -


