#!/usr/bin/env zsh

# Installation:
# - Run this script from dotfiles dir
# - Done!

# Link all the dots
echo ""
echo "Linking top-level dotfiles"
echo ""
for file in $(ls -I 'LICENSE' -I 'bootstrap' -I 'config' -I 'notes' -I 'vim'); do
  echo $(pwd)/$file
  echo "-> $HOME/.$file"
  ln -sfF "$(pwd)/$file" "$HOME/.$file"
done
echo ""


