#!/bin/bash

#
# version:
#   11-23-2021
#
# author:
#	  Bjarke Brodin <bjarke@brodin.dk>
#
# Configures Ubuntu 20.04 and GNOME environment
#
# After running script, TODO:
#  [ ] Install chrome
#  [ ] Verify that hardware works correctly and fix drivers if needed
#

NAME="Bjarke Brodin"
EMAIL="bjarke@brodin.dk"


# Add ppa's and their respective gpg keys for some things

# Alacritty
suo apt-add-repository -y ppa:aslatter/ppa

# Spotify
curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | sudo apt-key add - 
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list

# sbt
echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add


# Update system
sudo apt update -y && \
sudo apt upgrade -y


# Install some prerequisite packages
sudo apt-get install -y \
  gtk-vim \
  zsh \
  tldr \
  curl \
  gcc \
  make \
  cmake \
  gnome-tweak-tool \
  zip \
  unzip \
  fd-find \
  git \
  alacritty \
  spotify-client \
  openjdk-17-jdk \
  scala \
  sbt \
  gradle \
  golang \
  nodejs \
  npm \
  valgrind

# Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh


# Make alacritty our default terminal via symlink hacks
sudo mv /usr/bin/gnome-terminal /usr/bin/gnome-terminal.bak && \
sudo ln -s /usr/bin/alacritty /usr/bin/gnome-terminal


# Make sure we have .zsh-system-clipboard available
git clone https://github.com/kutsan/zsh-system-clipboard ~/.zsh/plugins/zsh-system-clipboard


# Install [github CLI](https://github.com/cli/cli/blob/trunk/docs/install_linux.md)
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null && \
sudo apt update -y && \
sudo apt install gh -y && \


# Prezto!
echo "#!/bin/zsh" > "$HOME/.local_env"
chsh -s /bin/zsh $(echo $USER) && \
git clone --recursive git@github.com:bjarkebrodin/prezto.git "${ZDOTDIR:-$HOME}/.zprezto" && \
setopt EXTENDED_GLOB && \
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done


# Set java home in .local_env
echo "export JAVA_HOME=$(java -XshowSettings:properties -version 2>&1 > /dev/null | grep 'java.home' | cut -d'=' -f 2 | tr " " "\0")" >> "$HOME/.local_env"

# IntelliJ IDEA
sudo snap install intellij-idea-community --classic

# VSCode
snap install code --classic

# Get & set the dots
git clone git@github.com:bjarkebrodin/bunbun.git ~/Dotfiles && \
cd ~/Dotfiles && \
chmod +x ./bootstrap && \
./bootstrap


# Configure git
git config --global user.name $NAME
git config --global user.email $EMAIL


# Install fonts
curl -L "https://github.com/be5invis/Iosevka/releases/download/v11.1.0/super-ttc-iosevka-11.1.0.zip" > ~/Downloads/iosevka.zip && \
unzip ~/Downloads/iosevka.zip && \
sudo mv ~/Downloads/*.ttc /usr/share/fonts/ && \ 
sudo mv ~/Downloads/*.ttf /usr/share/fonts/ && \ 
sudo fc-cache


# Install themes
THEME_VARIANT="Nordic-darker-v40"
curl -L "https://github.com/EliverLara/Nordic/releases/download/v2.1.0/$THEME_VARIANT.tar.xz" > ~/Downloads/nordic.tar.xz && \
sudo tar -xvf ~/Downloads/nordic.tar.xz --directory=/usr/share/themes && \
rm ~/Downloads/nordic.tar.xz 

dconf write /org/gnome/shell/extensions/user-theme/name "'$THEME_VARIANT'"
dconf write /org/gnome/desktop/interface/gtk-theme "'$THEME_VARIANT'"


# Get & set wallpaper
ext=".png"
#curl -L https://w.wallhaven.cc/full/dp/wallhaven-dpo38l.jpg > "$HOME/.local/share/backgrounds/wallpaper$ext"
dconf write /org/gnome/desktop/background/picture-uri "'file://$HOME/.local/share/backgrounds/wallpaper$ext'"
dconf write /org/gnome/desktop/screensaver/picture-uri "'file://$HOME/.local/share/backgrounds/wallpaper$ext'"

# Reconfigure the dock
gnome-extensions disable ubuntu-dock@ubuntu.com

# Set input modes
dconf write /org/gnome/desktop/input-sources/sources "[('xkb', 'us'), ('xkb', 'dk')]"

# Disable old keybindings
dconf write /org/gnome/desktop/wm/keybindings/show-desktop "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-up "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-down "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-last "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-applications "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-applications-backward "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-panels "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-panels-backward "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-windows "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-windows-backward "@as []"
dconf write /org/gnome/desktop/wm/keybindings/cycle-panels "@as []"
dconf write /org/gnome/desktop/wm/keybindings/cycle-panels-backward "@as []"
dconf write /org/gnome/desktop/wm/keybindings/cycle-group "@as []"
dconf write /org/gnome/desktop/wm/keybindings/cycle-group-backward "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-group "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-group-backward "@as []"
dconf write /org/gnome/desktop/wm/keybindings/minimize "@as []"
dconf write /org/gnome/desktop/wm/keybindings/maximize "@as []"
dconf write /org/gnome/desktop/wm/keybindings/begin-move "@as []"
dconf write /org/gnome/desktop/wm/keybindings/begin-resize "@as []"
dconf write /org/gnome/desktop/wm/keybindings/toggle-maximize "@as []"
dconf write /org/gnome/desktop/wm/keybindings/unmaximize "@as []"
dconf write /org/gnome/desktop/wm/keybindings/activate-window-menu "@as []"
dconf write /org/gnome/desktop/wm/keybindings/panel-main-menu "@as []"
dconf write /org/gnome/shell/keybindings/focus-active-notification "@as []"
dconf write /org/gnome/shell/keybindings/open-application-menu "@as []"
dconf write /org/gnome/shell/keybindings/toggle-application-view "@as []"
dconf write /org/gnome/shell/keybindings/toggle-message-tray "@as []"
dconf write /org/gnome/shell/keybindings/toggle-overview "@as []"
dconf write /org/gnome/settings-daemon/plugins/media-keys/window-screenshot-clip "@as []"
dconf write /org/gnome/settings-daemon/plugins/media-keys/window-screenshot "@as []"
dconf write /org/gnome/settings-daemon/plugins/media-keys/screenshot-clip "@as []"
dconf write /org/gnome/settings-daemon/plugins/media-keys/screenshot "@as []"
dconf write /org/gnome/settings-daemon/plugins/media-keys/screenreader "@as []"
dconf write /org/gnome/settings-daemon/plugins/media-keys/logout "@as []"
dconf write /org/gnome/mutter/wayland/keybindings/restore-shortcuts "@as []"
dconf write /org/gnome/desktop/wm/preferences/mouse-button-modifier 'disabled'
dconf write /org/gnome/shell/keybindings/switch-to-application-1 "@as []"
dconf write /org/gnome/shell/keybindings/switch-to-application-2 "@as []"
dconf write /org/gnome/shell/keybindings/switch-to-application-3 "@as []"
dconf write /org/gnome/shell/keybindings/switch-to-application-4 "@as []"

# Set keybindings (important to do this after disabling, to avoit conflict weirdness)
dconf write /org/gnome/settings-daemon/plugins/media-keys/terminal "['<Super>Return']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/www "['<Super>b']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-down "['<Shift><Super>j']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-up "['<Shift><Super>k']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-left "['<Shift><Super>Left']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-right "['<Shift><Super>Right']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-1 "['<Shift><Super>1']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-2 "['<Shift><Super>2']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-3 "['<Shift><Super>3']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-4 "['<Shift><Super>4']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-1 "['<Super>1']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-2 "['<Super>2']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-3 "['<Super>3']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-4 "['<Super>4']"
dconf write /org/gnome/desktop/wm/keybindings/cycle-windows "['<Super>Tab']"
dconf write /org/gnome/desktop/wm/keybindings/cycle-windows-backward "['<Shift><Super>Tab']"
dconf write /org/gnome/desktop/wm/keybindings/close "['<Super>w']"
/org/gnome/desktop/wm/keybindings/minimize "['<Super>m']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/screensaver "['<Primary><Super>q']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/area-screenshot-clip "['<Shift><Super>4']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/area-screenshot "['<Shift><Super>s']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/screencast "['<Shift><Super>r']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/previous "['<Shift><Super>backslash']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/next "['<Super>backslash']"
dconf write /org/gnome/desktop/wm/keybindings/toggle-fullscreen "['<Super>f']"
dconf write /org/gnome/mutter/keybindings/toggle-tiled-left "['<Shift><Super>h']"
dconf write /org/gnome/mutter/keybindings/toggle-tiled-right "['<Shift><Super>l']"
dconf write /org/gnome/mutter/dynamic-workspaces 'false'
dconf write /org/gnome/desktop/wm/preferences/num-workspaces '4'
dconf write /org/gnome/shell/extensions/desktop-icons/show-home 'false'
dconf write /org/gnome/shell/extensions/desktop-icons/show-trash 'false'


